### ISSUE TITLE
The website only shows the JS for the index.md file

### ISSUE THREAD

**Issue by Steve0Greatness** [PoIygon/Scratch-Bookmarklets#2]
I think this may be because it hasn't been set up correctly.
If you'd like to see it for yourself, see: [https://scratchbookmarklets.vercel.app/](https://scratchbookmarklets.vercel.app/)
I'd suggest using github pages instead of vercel.

**Comment by PoIygon** [comment]
I am using GitHub pages it’s just that I decided to use vervel and now every single repository I have has been converted to vercel

**Comment by Steve0Greatness** [comment]
> I am using GitHub pages it’s just that I decided to use vervel and now every single repository I have has been converted to vercel

ah, yes, because this isn't broken:
![Screenshot 2021-05-29 5 38 21 PM](https://user-images.githubusercontent.com/75220768/120088382-b643d380-c0a4-11eb-9fd1-a3e42872649f.png)

**Comment by PoIygon** [comment]
> > I am using GitHub pages it’s just that I decided to use vervel and now every single repository I have has been converted to vercel
> 
> ah, yes, because this isn't broken:
> ![Screenshot 2021-05-29 5 38 21 PM](https://user-images.githubusercontent.com/75220768/120088382-b643d380-c0a4-11eb-9fd1-a3e42872649f.png)

Vercel doesn’t support markdown files

**Comment by Steve0Greatness** [comment]
> > > I am using GitHub pages it’s just that I decided to use vervel and now every single repository I have has been converted to vercel
> > 
> > 
> > ah, yes, because this isn't broken:
> > 
> 
> Vercel doesn’t support markdown files

then why are you using md?

**Comment by PoIygon** [comment]
> > > > I am using GitHub pages it’s just that I decided to use vervel and now every single repository I have has been converted to vercel
> > > 
> > > 
> > > ah, yes, because this isn't broken:
> > 
> > 
> > Vercel doesn’t support markdown files
> 
> then why are you using md?

Because my idiot self didn’t want to learn HTML back then

**Comment by TheGlassPenguin** [comment]
> > > > > I am using GitHub pages it’s just that I decided to use vervel and now every single repository I have has been converted to vercel
> > > > 
> > > > 
> > > > ah, yes, because this isn't broken:
> > > 
> > > 
> > > Vercel doesn’t support markdown files
> > 
> > 
> > then why are you using md?
> 
> Because my idiot self didn’t want to learn HTML back then
I can convert the .md file to an HTML file if ya want
